language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
env: PLONE_VERSION=4.3
install:
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py
  - bin/buildout annotate
  - bin/buildout -Nq
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
